log:
  level: info
  format: text

serve:
  api:
    port: 4468
  proxy:
    port: 4469

pipeline:
  authenticators:
    - id: "noop_authenticator"
      type: noop
    - id: "anonymous_authenticator"
      type: anonymous
    - id: "unauthorized_authenticator"
      type: unauthorized
    - id: "kratos_session_authenticator"
      type: authentication_data
      config:
        identity_info_endpoint:
          url: http://127.0.0.1:4433/sessions/whoami
          retry:
            max_delay: 300ms
            give_up_after: 2s
        authentication_data_source:
          - cookie: ory_kratos_session
            transform_to: 
        session:
          attributes_from: "@this"
          subject_from: "identity.id"
    - id: "hydra_authenticator"
      type: oauth2_introspection
      config:
        introspection_endpoint:
          url: http://hydra:4445/oauth2/introspect
          retry:
            max_delay: 300ms
            give_up_after: 2s
          auth:
            type: basic-auth
            config:
              user: foo
              password: bar
        introspection_response_assertions:
          issuers:
            - http://127.0.0.1:4444/
          scopes:
            - foo
            - bar
          audience:
            - bla
        session:
          attributes_from: "@this"
          subject_from: "identity.id"
    - id: "jwt_authenticator"
      type: jwt
      config:
        jwks_endpoint:
          url: foo/token
          method: GET
        jwt_token_from:
          - header: Authorization
            strip_prefix: Bearer
        jwt_assertions:
          audience:
            - bla
          scopes:
            - foo
          allowed_algorithms:
            - RSA
          issuers:
            - bla
        session:
          attributes_from: "@this"
          subject_from: "identity.id"
        cache_ttl: 5m
  authorizers:
    - id: "allow_all_authorizer"
      type: allow
    - id: "deny_all_authorizer"
      type: deny
    - id: "keto_authorizer"
      type: remote
      config:
        endpoint:
          url: keto
          method: POST
          headers:
            foo-bar: "{{ .Subject }}"
        payload: "https://bla.bar"
        forward_response_headers:
          - bla-bar
  hydrators:
    - id: "subscription_hydrator"
      type: default
      config:
        endpoint:
          url: foo.bar
          method: GET
        payload: http://foo
        headers:
          bla: bla
    - id: "profile_data_hydrator"
      type: default
      config:
        endpoint:
          url: http://profile
        headers:
          foo: bar
  mutators:
    - id: "jwt"
      type: jwt
      config:
        issuer: http://issuer
        ttl: 5m
    - id: "bla"
      type: header
      config:
        headers:
          foo-bar: bla
    - id: "blabla"
      type: cookie
      config:
        cookies:
          foo-bar: '{{ .ID }}'
  error_handlers:
    - id: default_error
      type: json
      config:
        verbose: false
    - id: authenticate_on_unauthorized_or_forbidden
      type: redirect
      config:
        to: http://127.0.0.1:4433/self-service/login/browser
        return_to_query_param: return_to
        when:
          - error:
              - unauthorized
              - forbidden
            request:
              header:
                accept:
                  - text/html

rules:
  default:
    authenticators:
      - id: deny_all_authorizer
    authorizer:
      id: unauthorized_authenticator
    error_handlers:
      - id: authenticate_on_unauthorized_or_forbidden
      - id: default_error

  providers:
    file:
      src: test_rules.yaml

    docker:
      endpoint: docker.sock
      timeout: 1s
    kubernetes_crd:
      namespaces:
        - fooo
      label_selector: foobar
